### ISSUE TITLE
Start your own private network needs to be updated

### ISSUE THREAD

**Issue by bkchr** [substrate-developer-hub/tutorials#1]
The telemetry CLI parameter was updated recently. The tutorial needs to be adapted.

See: https://github.com/paritytech/substrate/issues/5552

**Comment by JoshOrndorff** [comment]
The tutorial instructs to use `v2.0.0-alpha.5` (or alpha.3 if you're not on the latest stable docs). The change in parsing telemetry args was merged after `v2.0.0-alpha.5`. So it will be updated before we release the next version of this tutorial. Thanks for the heads up.

**Comment by bkchr** [comment]
Yeah, I'm not the user. I just reposted it here :P

**Comment by bkchr** [comment]
But fair point ;)

**Comment by JoshOrndorff** [comment]
Closing in favor of #11
