### ISSUE TITLE
Update tutorials to alpha.6

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/tutorials#11]
Substrate `v2.0.0-alpha.6` was [tagged recently](https://github.com/paritytech/substrate/releases/tag/v2.0.0-alpha.6). We should update all of our tutorials to use the new APIs.

A heads up specifically about the start a private network tutorial taken from #1

> The telemetry CLI parameter was updated recently. The tutorial needs to be adapted.
>
> See: paritytech/substrate#5552

**Comment by danforbes** [comment]
@JoshOrndorff is this closed with #13?
