### ISSUE TITLE
Building failed.

### ISSUE THREAD

**Issue by herou** [substrate-developer-hub/tutorials#44]
Hello guys,

I am trying to build in release either in developing but I am facing the issue below: 
![image](https://user-images.githubusercontent.com/13895430/83338055-c32abd00-a2c0-11ea-83fd-0e1511f5bac3.png)

**Comment by danforbes** [comment]
I believe I have seen problems like this related to the Rust version that is being used. Can you please share this?
```
~: rustc --version
rustc 1.42.0 (b8cedc004 2020-03-09)
~: cargo --version
cargo 1.42.0 (86334295e 2020-01-31)
```

**Comment by herou** [comment]
~:  rustc --version
rustc 1.43.1 (8d69840ab 2020-05-04)
~: cargo --version
cargo 1.43.0 (2cbe9048e 2020-05-03)

I do not see any main difference between your versions and mine :/

**Comment by danforbes** [comment]
Can you share some steps to reproduce this issue? Are you building [the node template](https://github.com/substrate-developer-hub/substrate-node-template)? What tutorial are you following and what step are you at?

**Comment by herou** [comment]
I am following this tutorial: https://www.substrate.io/tutorials/create-your-first-substrate-chain/v2.0.0-alpha.8/setup

and then I ran these commands: 
# Update Rust
rustup update nightly
rustup update stable

# Add Wasm target
rustup target add wasm32-unknown-unknown --toolchain nightly

cd substrate-node-template/
git checkout -b my-first-substrate-chain
cargo build --release

That's it.

**Comment by herou** [comment]
Another screenshot which may help: 
![image](https://user-images.githubusercontent.com/13895430/83338226-63351600-a2c2-11ea-915f-859045f71d88.png)

**Comment by danforbes** [comment]
Okay, it looks like you're building `v2.0.0-rc` of the node template, but following `v2.0.0-alpha.8` of the tutorial, which may be a problem. [Here is the current version of that tutorial](https://www.substrate.io/tutorials/create-your-first-substrate-chain/v2.0.0-rc2). Did you do [the `source ~/.cargo/env` step](https://www.substrate.io/tutorials/create-your-first-substrate-chain/v2.0.0-rc2/setup#compiling-substrate)?

**Comment by herou** [comment]
The initial commands are the same for both versions (v2.0.0-rc and  v2.0.0-alpha.8). Yes, I executed also the source ~/.cargo/env command.

**Comment by danforbes** [comment]
Okay, it looks like you're running on Windows, correct? Let me see if I can find someone with a Windows machine who may be able to replicate this issue.

**Comment by herou** [comment]
Yes, I am using Windows but I am using Windows subsystem for Linux.

**Comment by danforbes** [comment]
Helpful information, thanks for the context :+1:

**Comment by danforbes** [comment]
I asked in [our Substrate Technical channel on Riot](https://riot.im/app/#/room/!HzySYSaIhtyWrwiwEV:matrix.org) and the suggestion was, indeed, that you need to downgrade your Rust nightly to 15.05. Here are some commands that someone else provided me with but I have not tried myself:
```
rustup install nightly-2020-05-15
rustup override set nightly-2020-05-15
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-05-15
```

**Comment by danforbes** [comment]
Linking to the upstream Issue in Substrate https://github.com/paritytech/substrate/issues/6167.

**Comment by herou** [comment]
@danforbes  it worked. Thank you!

**Comment by lam-my** [comment]
### install or update rust：
cmd: 
rustup update
rustup self update
rustup install nightly
rustup default nightly
----------------------------------------------------------------------
### or  大陆：
***使用USTC 的rust mirror***
echo "export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static" >> ~/.bashrc
echo "export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup" >> ~/.bashrc
source ~/.bashrc

***使用cargo代理，增快rust下载速度***
cat >~/.cargo/config <<EOF
[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"
EOF

***安装rust nightly版本，并默认使用nightly版本***
rustup install nightly
rustup default nightly

*** 安装RLS组建***
rustup component add rls --toolchain nightly
rustup component add rust-analysis --toolchain nightly
rustup component add rust-src --toolchain nightly

***安装racer***
cargo install racer
