### ISSUE TITLE
Encountered consensus error when trying to launch my private network. 

### ISSUE THREAD

**Issue by herou** [substrate-developer-hub/tutorials#46]
Hello,

I am following this tutorial: https://www.substrate.io/tutorials/start-a-private-network/v2.0.0-rc2/customchain and I am facing this issue:
![image](https://user-images.githubusercontent.com/13895430/83356479-c082a300-a366-11ea-836f-507fde8a4da2.png)
Can somebody let me know what I am doing wrong? I am using the pre-generated keys.

**Comment by danforbes** [comment]
Are you sure you are using v2.0.0-rc2? This is an issue that existed on v2.0.0-alpha.8. Ref: https://github.com/paritytech/substrate/issues/6052. I am also noticing the error that says `Block ... exists in chain but...` - that error should not exist. You may want to go back and make sure you have followed all the steps correctly and are not seeing any errors or funny warnings.

**Comment by herou** [comment]
I checked the tag version and yes, I am using the alpha one :/

**Comment by danforbes** [comment]
When I was preparing the `rc2` tutorials, I remember seeing a problem like this but it related to the fact that I was not using the right keys. That being said, I don't believe I saw the error you are seeing related to not being able to find a block. You should purge your chain state `rm -fr /tmp/node0*` and start from the beginning. If something is unclear, you can ask in [our Substrate Technical Riot channel](https://riot.im/app/#/room/!HzySYSaIhtyWrwiwEV:matrix.org). FWIW the "right" way to purge the chain is by using `./target/release/node-template --purge-chain` but I have found that this can leave behind some old state that can cause unexpected behavior.
