### ISSUE TITLE
Can't connect polkadot ui to local subtrate node

### ISSUE THREAD

**Issue by 01willtx** [substrate-developer-hub/tutorials#47]
Using tutorial 1: https://www.substrate.io/tutorials/create-your-first-substrate-chain/v2.0.0-rc2/interact

After starting node and ui, the ui is not connecting to the node and there is no data displayed from the previous steps in the tutorial. The only tab in the UI is "Settings".

### Steps to reproduce:

1.  start node `./target/release/node-template --dev`

2. start ui via docker: `docker run --rm -it --name polkadot-ui -e WS_URL=ws://someip:9944 -p 80:80 chevdor/polkadot-ui:latest`

3. browse to http://localhost/#/settings and set the endpoint to ws://127.0.0.1:9944

[update] I noticed the node seems to still be importing...this has been going on for a while so I don't know if that means the node isn't ready to accept connections.

      Imported #2258 (0x2568…a282)

**Comment by danforbes** [comment]
I have never used the UI via Docker and I'm inclined to believe that is the root of your problem. You may want to try one of the other ways of using the UI ([the deployed instance](https://polkadot.js.org/apps/#/explorer), running it directly on your computer, etc) or opening an Issue on [the repo for the Docker image](https://polkadot.js.org/apps/#/explorer).

**Comment by JoshOrndorff** [comment]
>  Imported #2258 (0x2568…a282)

That just means that your node has heard of block 2258 and added it to its database. It does not mean your node is performing a major sync operation. These messages are normal and the UI should still work. If you're using the node template, as the tutorial instructs, blocks are produced every 6 seconds which means that to produce 2258 blocks your chain has been running for almost 4 hours. Is that what you were expecting? If not, you may benefit from purging your chain and trying again.

I agree with @danforbes remove the docker ui from the setup and try again. If you still have trouble, we can help you. If that solves your problem then chevdor (who created the docker image) should be able to help get the image working for you.

**Comment by 01willtx** [comment]
Hi! Thanks for the responses. I stopped docker and proceeded with the tutorial steps on how to host the ui locally. This works, instructions here: https://github.com/polkadot-js/apps#development

@JoshOrndorff yes I just let it run thinking it needed to finish syncing :-)
