### ISSUE TITLE
 two packages named `pallet-template` in this workspace:

### ISSUE THREAD

**Issue by herou** [substrate-developer-hub/tutorials#50]
I am following this tutorial: https://www.substrate.io/tutorials/pallet-in-own-crate/v2.0.0-rc2#install-the-node-template and I am facing the issue described below:

![image](https://user-images.githubusercontent.com/13895430/83463649-f27f2c80-a46e-11ea-999f-dfc79a8c60e1.png)

If you see, I have cloned the substrate-pallet-template repo into pallets package:
![image](https://user-images.githubusercontent.com/13895430/83463725-2f4b2380-a46f-11ea-83e0-0a7ea57f968b.png)

Am I doing something wrong?

**Comment by danforbes** [comment]
I think you missed this step https://www.substrate.io/tutorials/pallet-in-own-crate/v2.0.0-rc2#renaming-your-crate

**Comment by herou** [comment]
I would highlight (mention) that name has to be changed.
