### ISSUE TITLE
Finished all  tutorials. What is next?

### ISSUE THREAD

**Issue by herou** [substrate-developer-hub/tutorials#52]
Hi @danforbes, I would like to thank you for your support. Because of you, I finished all the substrate tutorials. 
Now I am looking for something else to work on.
Do you have any suggestions?

**Comment by JoshOrndorff** [comment]
Have you explored the substrate recipes? https://substrate.dev/recipes hosts the text. Lots of code examples in the repository https://github.com/substrate-developer-hub/recipes/

**Comment by danforbes** [comment]
Totally agree with Joshy and would also suggest using the knowledge you gain from the Recipes and think about contributing to [the GitCoin bounty challenge that opened recently](https://gitcoin.co/issue/Web3Foundation/build-polkadot/1/4391)!

**Comment by herou** [comment]
Thank you, guys. I appreciate your help.
