### ISSUE TITLE
error[E0424]: expected value, found module `self` installing subkey

### ISSUE THREAD

**Issue by 01willtx** [substrate-developer-hub/tutorials#53]
Tutorial https://substrate.dev/docs/en/tutorials/start-a-private-network/keygen error during subkey compile.

**Command:**
      cargo install --force subkey --git https://github.com/paritytech/substrate --tag v2.0.0-rc2

**Error:**
        Compiling sp-consensus-babe v0.8.0-rc2 (/Users/wlopez/.cargo/git/checkouts/substrate-7e08433d4c370a21/45b9f0a/primitives/consensus/babe)
      error[E0424]: expected value, found module `self`
         --> /Users/wlopez/.cargo/git/checkouts/substrate-    7e08433d4c370a21/45b9f0a/frame/support/src/traits.rs:913:11
          |
      911 | / bitmask! {
      912 | |     /// Reasons for moving funds out of an account.
      913 | |     #[derive(Encode, Decode)]
          | |              ^^^^^^ `self` value is a keyword only available in methods with a `self` parameter
      914 | |     pub mask WithdrawReasons: i8 where
      ...   |
      929 | |     }
      930 | | }
          | |_- this function has a `self` parameter, but a macro invocation can only access identifiers   it receives from parameters
          |
          = note: this error originate

I'll continue using the ui to generate the keys but thought I should report the issue.

**Comment by danforbes** [comment]
Are you on Windows by any chance? I have seen errors like this when Windows users are using the wrong Rust nightly build.

**Comment by JoshOrndorff** [comment]
Thanks for reporting this issue. It started with an update to the nightly compiler, which has since been reverted. See https://github.com/paritytech/substrate/issues/6167 for more details. Updating your rust toolchain should help. (Edit: commands to update toolchain below)

**Comment by danforbes** [comment]
@JoshOrndorff, can you provide the command that should be used (or a link to the command that can be used) to update the Rust toolchain?

**Comment by JoshOrndorff** [comment]
These commands should work for updating your rust toolchain. I took them from getsubstrate.io

```bash
rustup update
rustup default stable
rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly
```
