### ISSUE TITLE
[substrate] dot is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by VikXNebu** [substrate-developer-hub/tutorials#55]
Dear All,
I am very new to this scene and have depleted source in finding the answer for this error.

Please do advise or direct me for the following issue:-
1) I have followed the guide as per the tutorial on : Create Your First Substrate Chain
2) I'm using Windows 10 and followed the extra steps in installing the necessary applications
3) I'm unable to proceed further when I type ./target/release/node-template purge-chain --dev as it gives me the following error: 
'.' is not recognized as an internal or external command, operable program or batch file.

Appreciate your assistance.

Thank you.

**Comment by danforbes** [comment]
Are you using Windows Subsystem on Linux? The command you shared is a Linux style command so it makes sense that it would not work natively on Windows, but there are compatibility layers that can be used to allow you to execute commands like this one Windows. Unfortunately, I do not have access to a Windows machine so it's difficult for me to be of much help.

**Comment by VikXNebu** [comment]
Hi Danforbes,
Thank you for responding.

Im using Windows 10 and the following application was installed to try the tutorial:-
1) Visual Studio
2) Rust
3) LLVM
4) OpenSSL
5) CMake

But I think I noticed something when I try running rustup-init.exe, the installation was partly blocked by antivirus. 

Any assistance to get full running tutorial?

**Comment by wheresaddie** [comment]
I might suggest running/installing a Windows Subsystem for Linux (WSL) and running this via the linux WSL.
