### ISSUE TITLE
Is there any tutorial that can help me develop additional consensus algorithms to substrate?

### ISSUE THREAD

**Issue by Gauthamastro** [substrate-developer-hub/tutorials#56]
We are developing some new consensus algorithms, and I would like to test it on the substrate. Are there any tutorials or help available to make the development easier?

**Comment by danforbes** [comment]
There is a section of our Recipes on consensus that begins here https://substrate.dev/recipes/3-entrees/sha3-pow-consensus.html Please let me know if that's helpful or if you have any follow-ups.

**Comment by Gauthamastro** [comment]
> There is a section of our Recipes on consensus that begins here https://substrate.dev/recipes/3-entrees/sha3-pow-consensus.html Please let me know if that's helpful or if you have any follow-ups.

I went through the docs, but I am not able to figure out how to get the validator set from the staking module, and our consensus needs to send RPC calls to those validators to and receive messages based on these messages we can determine who will mine the next block. 
I am still not clear how to achieve this, can you please brief on how to implement RPC with the validators provided by the staking module?

**Comment by wheresaddie** [comment]
If I understand your question @Gauthamastro, you want to know how to get the validator set from the staking module? This boils down to just implementing `OnSessionEnding` correctly, as far as I understand staking should store the stake information for the `session will_apply_at` and use the information stored at session_ending to reward the current era..

**Comment by Gauthamastro** [comment]
> If I understand your question @Gauthamastro, you want to know how to get the validator set from the staking module? This boils down to just implementing `OnSessionEnding` correctly, as far as I understand staking should store the stake information for the `session will_apply_at` and use the information stored at session_ending to reward the current era.. 

Okay, I got what you mean. I think we get validators from `SessionHandler` in the pallet_session crate and these are validatorIDs but I want to send a message over the network to those validator's node. Is that possible?

I am thinking of getting peerID from the validatorID and using sc_network for registering a notification channel and send messages over that channel. I am not sure if it possible. 
What do you guys think?

**Comment by danforbes** [comment]
I think that should be possible, and in particular, you may want to review our documentation for the Authority Discovery pallet https://substrate.dev/rustdocs/v2.0.0-rc5/pallet_authority_discovery/index.html and for our network gossip module https://substrate.dev/rustdocs/v2.0.0-rc5/sc_network_gossip/index.html.

**Comment by Gauthamastro** [comment]
Yesss!!!, this is precisely what I was looking for.
