### ISSUE TITLE
Should This Repository Be Archived?

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/tutorials#57]

**Comment by danforbes** [comment]
I vote "aye".

**Comment by jimmychu0807** [comment]
@JoshOrndorff  @riusricardo  Just want to double check, are we not using this project anymore, and all the tutorials in substrate.dev are loaded from:

https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/tree/source/docs/tutorials ?

**Comment by riusricardo** [comment]
Yes, it should be archived.
