### ISSUE TITLE
Port or deprecate older tutorials

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/tutorials#6]
The following tutorials are all listed in the old substrate.dev tutorial index. They should either be dusted off and ported or deprecated. This issue is about making the decision, not actually updating anything.

- [ ] UTXO - @nczhu is overhauling the code presently. I'll leave the decision about the tutorial itself up to her.

- [x] Build a FrontEnd - After discussing with @Tbaut we've decided to deprecate this tutorial and replace it with a new one about building custom frontends starting from the [front-end template](https://github.com/substrate-developer-hub/substrate-front-end-template/). Here is a [dedicated issue](https://github.com/substrate-developer-hub/tutorials/issues/5) for that work.

- [ ] Substrate Collectibles Workshop aka Kitties - Last I heard, @shawntabrizi intends to update this tutorial after Substrate 2.0 is released. I suspect it will remain in its current docsify format, but it is also welcome in this repo, if this format is preferred.

- [x] Verifiable Credentials - This is significantly outdated. My preference is to deprecate.

- [x] TCR - @gautamdhameja and I overhauled the _code_ for this tutorial recently, but not the writeup or the UI. I'm willing to help with updating if Gautam wants to dust this one off. This could also be the combined with the Front End tutorial (see above).

**Comment by JoshOrndorff** [comment]
After discussing with @gautamdhameja we've decided on the following:
* Deprecate the verifiable credentials
* Deprecate the existing TCR tutorial, but replace it with one that teaches how to build a UI based on the front-end -template, and uses this more-updated TCR code https://github.com/joshorndorff/tcr-substrate . https://github.com/substrate-developer-hub/tutorials/issues/5 is for that tutorial.

**Comment by gautamdhameja** [comment]
Also, we decided to move out old TCR repo from the devhub org in favour of the new TCR code and repo from @JoshOrndorff.

**Comment by JoshOrndorff** [comment]
I've decided to deprecate the Collectibles tutorial for the time being. @shawntabrizi, we would be happy to have that tutorial back if/when you want to update it.

@nczhu and I have done some significant work on the utxo-workshop recently and transformed it into a more completely bitcoin-like chain. Several parts of that work will be ported into the recipes, and some parts of it will become video tutorials. Porting bits of it to this tutorial repo is also welcome, but no concrete plans to do that in the short term. Thus I'm closing this.

**Comment by shawntabrizi** [comment]
I will move the collectables tutorial back to my repository then
