### ISSUE TITLE
Links from tutorials to KB are broken

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/tutorials#7]
This issue is moved from https://github.com/paritytech/substrate.io/issues/38

https://staging.substrate.io/tutorials/add-a-pallet/v2.0.0-alpha.5

- [x] "FRAME"
- [x] "Creating Your First Substrate Chain Tutorial"
- [x] "demonstration Substrate node runtime"
- [x]  "Genesis Configuration"

@thisisvilla Can you please fix one of these (or explain how to properly write the link) and I'll do the rest of them.

**Comment by JoshOrndorff** [comment]
The first two are solved in #8. The third one appears not to be broken. The doc linked in the fourth is not present in the new knowledgebase. I've opened https://github.com/substrate-developer-hub/knowledgebase/issues/40 to port it.

**Comment by maxsupera** [comment]
@JoshOrndorff can you elaborate on what the problem with the links are? in general, you just put the url path. `/tutorials/add-a-pallet/v2.0.0-alpha.5#file-structure`, or `/tutorials/build-a-dapp/v2.0.0-alpha.5/front-end`, for example

**Comment by JoshOrndorff** [comment]
I wasn't sure how the links worked cross-repository. Specifically how to link from tutorials that live in this repo to KB articles that live in the KB repo. My initial attempt in #8 used relative paths, but it sounds like that's incorrect from your description. I've now updated it to use absolute paths. If #8 looks good, then there is no problem.

**Comment by JoshOrndorff** [comment]
I believe these are now all fixed in #8. Reviews appreciated.

**Comment by maxsupera** [comment]
Yep this has been reviewed and merged. closing this issue and the other issue at paritytech/substrate.io#38
